# -*- mode: ruby -*-
# vi: set ft=ruby :
NodeCount = 1

Vagrant.configure("2") do |config|
  
  #config.vm.provision "shell", path: "bootstrap.sh"

  (1..NodeCount).each do |i|
    config.vm.define "controlled-vm#{i}" do |controlledvm|
      controlledvm.vm.box = "ubuntu/xenial64"
      controlledvm.vm.hostname = "controlled-vm#{i}.wayuslatan.com"
      controlledvm.vm.network "public_network", type: "dhcp"
      controlledvm.vm.provider "virtualbox" do |v|
        v.name = "controlled-vm#{i}"
        v.memory = 1024
        v.cpus = 1
      end
      config.vm.synced_folder "D:/shared", "/mnt"
      config.vm.provision "shell", path: "bootstrap.sh"
    end
  end
end
