# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  config.vm.define "ansible-nginx1" do |ansiblenginx1|
    ansiblenginx1.vm.box = "ubuntu/xenial64"
    ansiblenginx1.vm.hostname = "ansibl-nginx1.wayuslatan.com"
    ansiblenginx1.vm.network "public_network", type: "dhcp"
    ansiblenginx1.vm.provider "virtualbox" do |v|
      v.name = "ansible-nginx1"
      v.memory = 2048
      v.cpus = 2
    end
    #ansiblenginx1.vm.provision "shell", path: "bootstrap_ansiblenginx1.sh"
    config.vm.synced_folder "D:/shared", "/mnt"
  end
end
