# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  config.vm.define "ansible-nginx1" do |ansible-nginx1|
    ansible-nginx1.vm.box = "ubuntu/xenial64"
    ansible-nginx1.vm.hostname = "ansible-nginx1"
    ansible-nginx1.vm.network "public_network", type: "dhcp"
    ansible-nginx1.vm.provider "virtualbox" do |v|
      v.name = "ansible-nginx1"
      v.memory = 2048
      v.cpus = 2
    end
    ansible-nginx1.vm.provision "shell", path: "bootstrap_ansible-nginx1.sh"
  end

  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "ansible-nginx1"

  config.vm.network "public_network", type: "dhcp"

  # default router
  config.vm.provision "shell",
  run: "always",
  inline: "route add default gw 192.168.2.1"

  # delete default gw on eth0
  config.vm.provision "shell",
  run: "always",
  inline: "eval `route -n | awk '{ if ($8 ==\"eth0\" && $2 != \"0.0.0.0\") print \"route del default gw \" $2; }'`"

  config.vm.synced_folder "D:/shared", "/mnt"
  #config.vm.provision "shell",
  #inline: "sudo mount.cifs //192.168.2.35/shared /mnt -o user=worawat,password=1234"
	
  config.vm.provision "shell", inline: "systemctl disable ufw" 
  config.vm.provision "shell", inline: "systemctl stop ufw" 
  config.vm.provision "shell", inline: "swapoff -a"
	
  #config.vm.customize ["modifyvm", :id, "--memory", 2048]
  #config.vm.customize ["modifyvm", :id, "--cpus", 2]
   
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
  end

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  #config.vm.network "private_network", ip: "192.168.33.12"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
