# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  config.vm.define "ansible-nginx1" do |ansible-nginx1|
    ansible-nginx1.vm.box = "ubuntu/xenial64"
    ansible-nginx1.vm.hostname = "ansible-nginx1"
    ansible-nginx1.vm.network "public_network", type: "dhcp"
    ansible-nginx1.vm.provider "virtualbox" do |v|
      v.name = "ansible-nginx1"
      v.memory = 2048
      v.cpus = 2
    end
    #ansible-nginx1.vm.provision "shell", path: "bootstrap_ansible-nginx1.sh"
    config.vm.synced_folder "D:/shared", "/mnt"
  end
end
